name: gestion_espacios_app
description: ApplicaciÃ³n multiplataforma para el proyecto de final de grado del CFGS Desarrollo de Aplicaciones.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  url_launcher: ^6.0.3
  http: ^0.13.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: KoHo
      fonts:
        - asset: assets/fonts/KoHo-Bold.ttf
        - asset: assets/fonts/KoHo-BoldItalic.ttf
        - asset: assets/fonts/KoHo-ExtraLight.ttf
        - asset: assets/fonts/KoHo-ExtraLightItalic.ttf
        - asset: assets/fonts/KoHo-Italic.ttf
        - asset: assets/fonts/KoHo-Light.ttf
        - asset: assets/fonts/KoHo-LightItalic.ttf
        - asset: assets/fonts/KoHo-Medium.ttf
        - asset: assets/fonts/KoHo-MediumItalic.ttf
        - asset: assets/fonts/KoHo-Regular.ttf
        - asset: assets/fonts/KoHo-SemiBold.ttf
        - asset: assets/fonts/KoHo-SemiBoldItalic.ttf
